name: terragrunt-plan-all
description: Create a Terraform plan
author: Alina Freydina

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  tg_version:
    description: Required Terragrunt version
    required: false
    default: "0.52.4"
  tf_version:
    description: Required Terraform version
    required: false
    default: "1.5.7"
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: "0"
  label:
    description: A friendly name for this plan
    required: false
    default: ""
  add_github_comment:
    description: Add the plan to a GitHub PR
    required: false
    default: "true"
  destroy:
    description: Create a plan to destroy all resources
    required: false
    default: "false"

runs:
  using: docker
  image: docker://ghcr.io/fenikks/gh-actions-terragrunt@sha256:02c9ac72295b9b817bee8cea6b2b0877d4b1a8398eeeb1a16a8fd75fd49086be
  entrypoint: /entrypoints/tg_plan_all.sh

branding:
  icon: globe
  color: purple
